---
title: "Platforms and their Societal Impact. A Force for Good?"
author: "Giulia Solinas" 
date: 2021-06-22T21:13:14-05:00
categories: ["Platforms for good"]
tags: ["Platforms", "digitization"]
---
Platform businesses connect at least two sides, e.g. a buyer and a seller of a good or service, and have grown tremendously in importance in recent years. Indeed, platform business models form the basis of many household names in social media, ridesharing, operating systems and many more. The organization of such platforms is especially interesting because much of the value of a platform is created by complementary actors (individuals or firms) outside of the control of the platform business. This creates interesting dynamics between platform and complementors and between different platforms competing for the best complementors

On November 3rd 2021, I organized and moderated the online podium discussion **''Platforms and their Societal Impact. A Force for Good?''**  in cooperation with the [Centre of Advanced Studies](https://www.cas.uni-muenchen.de/index.html) of LMU Munich and the CAS Research Group ''Platforms as Organizations''.

I invited Dr. Anil Doshi (UCL/CAS Fellow), Fredrik Gulowsen (Nyby), Stina Heikkila (Boundaryless), Prof. Dr. Tobias Kretschmer (Head of CAS Research Group/LMU), and Prof. Gurneeta Vasudeva Singh (University of Minnesota/CAS Fellow) to discuss:

- The paradox(es) of the platforms' era.
- The solutions that platforms offer to address societal problems: decentralization, governance, and the management of the communities.


Recordings are available on the [LMU iTunes channel](https://www.cas.uni-muenchen.de/publikationen/casvideo/channel_miscellanea/index.html).

