---
title: "How can platforms help fight grand challenges?"
author: "Giulia Solinas" 
date: 2021-11-23T21:13:14-05:00
categories: ["Platforms for good"]
tags: ["Platforms", "digitization"]
---
How can platforms help fight grand challenges? How should they be designed to contribute to sustainability?**

Mission-driven platforms like Amnesty International Decoder and Humanitarian OpenStreetMap are on the rise. These societal platforms address challenges such as fighting poverty, education, climate actions, and sustainable cities and communities on a large scale and at speed by orchestrating an ecosystem and creating value for the market and society. 

Practice generally highlights that the platform’s philanthropic nature and the pro-social mission determine a very peculiar design and governance for those organizations. Yet, research in the field is still scarce.

On November 3rd 2021, I organized the workshop **''Societal Platforms: Between Markets and Grand Challenges''** with [Madeleine Rauch](https://www.rauchm.com/). (CBS), [Georg Reischauer](https://sites.google.com/view/greischauer/) (WU Vienna), Sebastian Geiger (LMU Munich) and in cooperation with the **Knowledge & Innovation Interest Group** of the [**Strategic Management Society**](https://www.strategicmanagement.net/).

We asked [Shaz Ansari](https://www.jbs.cam.ac.uk/faculty-research/faculty-a-z/shahzad-ansari/) (Cambridge University, UK), [Carliss Baldwin](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=6417) (Harvard Business School, US), [Anil Doshi](http://www.anilrdoshi.com/) (UCL, UK), [Dror Etzion](https://www.mcgill.ca/desautels/dror-etzion) (McGill University, CA), and [Gurneeta Vasudeva](https://carlsonschool.umn.edu/faculty/gurneeta-vasudeva-singh) (University of Minnesota, US) to express their take on the topic.

Recordings are available on the [SMS YouTube channel](https://youtu.be/O1_0MpZUPY0).

